### ISSUE TITLE
[ENHANCEMENT] - Support `.code-workspace` projects located on remotes

### ISSUE THREAD

**Issue by andrecavallari** [alefragnani/vscode-project-manager#486] opened 2021-04-08 22:08 UTC
- Extension version: Latest
- VSCode version: 1.55.0
- OS version: Ubuntu 20.10

**Steps to reproduce**

1. Create a new project from a ssh server, add
2. Add a new root directory
3. Save the workspace, for example: my-project.code-workspace
4. Save the project
5. Try to use the workspace project

I saw that the rootPath for the project in file `projects.json` is being created with some white spaces and some line breakings (\n)

For example, the path: `vscode-remote://ssh-remote+server/home/cavallari/dev/app.code-workspace` will save in projects.json as `vscode-remote://\n            ssh-remote+server         \n/home/cavallari/dev/roger.code-workspace`

**Comment by alefragnani** [comment] 2021-04-16 23:47
Hi @andrecavallari ,

The extension don’t support accessing `.code-workspaces` on _remotes_. If you need that, you must install the extension there. The way the extension works on remotes has been discussed in #323 .

But as suggested by @tyler36 in #487, and commented [here](https://github.com/alefragnani/vscode-project-manager/issues/487#issuecomment-821566097), maybe it’s possible to _transform_ the workspace path, IF it works similar to WSL.

Hope this helps

**Comment by andrecavallari** [comment] 2021-04-20 12:13
@alefragnani Hi, thanks for the reply.

It always worked fine here using a .code-workspace saved on remote server, it started crashing on latest updates.

After the new updates, it started saving the projects using `.code-workspace` like this:

``` 
{
  "name": "[SSH] - Roger GEM",
  "rootPath": "vscode-remote://\n                           ssh-remote+server\n                           /home/projects/roger.code-workspace",
  "paths": [],
  "group": "",
  "enabled": true
}
```

To fix this and get this project working corectly I need to edit the `projects.json` file and remove the whitespaces and `\n` in the code, converting to this:

``` 
{
  "name": "[SSH] - Roger GEM",
  "rootPath": "vscode-remote://ssh-remote+server/home/projects/roger.code-workspace",
  "paths": [],
  "group": "",
  "enabled": true
}
```

**Comment by alefragnani** [comment] 2021-04-20 13:20
Hi @andrecavallari ,

That's weird (the error) and unexpected (to work this way) 😆 . 

About the error, because nothing has changed (in the recent 12.1.0 release - April 4th) for any remote, other than Codespaces. I reinstalled version 12.0.0 (Nov 2020), and it saved the exact same _erroneous_ path.

I could reproduce the error using WSL and Docker, and it appears to be happening for almost an year (based on logs).

The good new is, it should be fixed in the next release 😬 

Thank you

**Comment by andrecavallari** [comment] 2021-04-20 19:19
@alefragnani, yes, it started about nov/dec 2020, I dont remember exactly when, but the project reference gets lost with this issue, I've produced the issue using an internal network based on Linux, didnt know WSL and Docker had same issue, but I am happy to know this will be fixed, and thank YOU for supporting this plugin, wich I consider one of the "must have" vs code plugins, and one of the most used by me

**Comment by alefragnani** [comment] 2021-04-20 23:13
Thanks! I’m glad to know you like the extension 👍

**Closed** 2021-04-29 15:32 UTC
Labels: enhancement, remote
