### ISSUE TITLE
Add project for the first time very slow

### ISSUE THREAD

**Issue by mhy-web** [alefragnani/vscode-project-manager#225] opened 2018-10-01 03:49 UTC
Used for the first time special slow,  The reason may be looking for a configuration file, you can optimize it?

**Comment by alefragnani** [comment] 2018-10-03 11:11
Hi @mhy-web ,

Do you mean the _automatic detection_ of Git, SVN, Mercurial and VS Code projects? If yes, how is your settings, and how many projects where detected? Or ar you using the simpler `Save Project` command?

Hope this helps

**Comment by mhy-web** [comment] 2018-10-05 03:27
When I install vscode in a new Mac , then I want config my vscode and install sync plugin. when the plugin is indtalled and reloaded, then open a git project and  run  command `save project`, very slow.
That happened when the projcet list has nothing.

**Comment by alefragnani** [comment] 2019-04-03 03:49
Looking at the `Save Project` command, I couldn't find anything which would slow down the process. It simply saves a text file with a few lines (`.json`) and activates the Status Bar.]

You did say you are using a sync extension to keep your config syncronized between different machines. I don't know which one you are using, but if it has any kind of _auto-upload/downlown_ config, this could be the reason. 

I suggest you to disable this sync extension and try to reproduce the issue. If it does not happen, the sync extension will be the cause of the delay.

Hope this helps

**Comment by alefragnani** [comment] 2020-03-13 00:47
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.

**Closed by alefragnani** 2020-03-13 00:47 UTC
Labels: enhancement, need more info, performance
