### ISSUE TITLE
Git baseFolders doesn't seem to be working on mac OS

### ISSUE THREAD

**Issue by codingmatty** [alefragnani/vscode-project-manager#94] opened 2017-02-21 02:18 UTC
I have tried a few different things, but I assume something like this was supposed to work:

```javascript
"projectManager.git.baseFolders": [
    "~/Projects/"
],
```
or at least this:
```javascript
"projectManager.git.baseFolders": [
    "/Users/<username>/Projects/"
],
```

**Comment by RobertDessin** [comment] 2017-02-22 17:23
:+1:

**Comment by alefragnani** [comment] 2017-02-22 23:50
Hi @codingmatty ,

Yes, it should work. It wil look for _git repos_ inside that folder, recursively. Just remember that in Mac/Linux, the folders are _case sensitive _.

@BonDoQ , could you help me again, and test this config in your Mac :smiley: ?

**Comment by TalAmitOS** [comment] 2017-03-04 16:36
Same issue here.

**Comment by oarrabi** [comment] 2017-03-05 12:28
I am facing a similar issue. When I refresh the projects its start looking but it stops and only shows a subset of the git projects I have.

Here are my settings

```
    "projectManager.vscode.baseFolders": [
        "/Users/.../Documents"
    ],
    "projectManager.vscode.maxDepthRecursion": 10,
    "projectManager.cacheProjectsBetweenSessions": true,
    "projectManager.showProjectNameInStatusBar": true
```

**Comment by TalAmitOS** [comment] 2017-03-05 14:19
So, it worked for me with this setting. Just like @alefragnani wrote (sorry for the miss understanding):
```
"projectManager.git.baseFolders": [
        "/Users/user.name/Projects/"
    ]
```

**Comment by alefragnani** [comment] 2017-03-05 18:11
Good to know @TalAmitOS 🎉 

What was the catch? Case-sensitive folders?

**Comment by TalAmitOS** [comment] 2017-03-05 19:14
Actually nothing new. I just replace:
```
"projectManager.git.baseFolders": [
    "~/Projects/"
]
```
With:
```
"projectManager.git.baseFolders": [
        "/Users/user.name/Projects/"
]
```
And refresh the projects list.

**Comment by alefragnani** [comment] 2017-03-06 03:50
@codingmatty  @RobertDessin @oarrabi are your git projects right at the _base_ folder, or in any subfolder?

By the way, the _detection_ is fairly simple. It just looks for a folder called `.git` with a file `config` inside. It does not make any kind of _git repo validation/authentication_. Also, if you use the `cacheProjectsBetweenSessions` as `true`, you should run the `Refresh` command, if you update the `baseFolders` setting.

Let me know if you have any success

**Comment by RobertDessin** [comment] 2017-03-06 13:25
@alefragnani ok, cool. Actually with `"projectManager.cacheProjectsBetweenSessions" : true` it suddenly works. great. Thanks

**Comment by alefragnani** [comment] 2017-03-09 02:15
- [X] @RobertDessin 
- [X] @TalAmitOS 
- [ ] @codingmatty 
- [ ] @oarrabi

**Comment by robsaunders** [comment] 2017-05-03 07:15
I also had this problem, and only solved it by the suggestions above, setting `"projectManager.cacheProjectsBetweenSessions": true` and stating the full, absolute path (including your actual username, so for me it was `"/Users/rob/Projects/"`).

It would be great if we could add this to the documentation for the plugin, or better yet add support for ~ or $home, as dictated by the documentation currently. Also mentioning the caching requirement would help other users.

Thanks again for this fantastic plugin!

**Comment by alefragnani** [comment] 2017-05-04 00:15
Hi @robsaunders ,

Yes, this settings `xxx.baseFolders` only works with _full path_, at least for now 😄 . The support for _variables_ will be addressed in #88 .

About the directories that are not recognized, well, the detection is made _checking_ for `git` repositories, which means that it contains `.git` directory with a `config` file inside. It don't run any `git` command (like `init`) to be sure. It is just a _lazy_ check. There is no setting available to _any kind of folder_ yet, and I don't know if this would be a good idea (thinking about the side effects).  If you think this scenario is a _must have_, pleas open another issue and I could handle it with another setting.

I will close this issue now, since the use of _variables_ for `xxx.baseFolders` will be treated in #88.

**Closed by alefragnani** 2017-05-04 00:15 UTC
Labels: bug, help wanted

**Comment by pookdeveloper** [comment] 2020-08-02 17:13
Not work for me

> "projectManager.git.baseFolders": [
        '/Users/davidgarcia/Desktop/ionic'
    ]

**Comment by alefragnani** [comment] 2020-08-02 23:26
Hi @pookdeveloper ,

Could you provide more details about what are,you experiencing?

Does it show the `Refresh` notification or not? is the Side Bar visible? Are you using using the correct _case_ for the path?

**Comment by pookdeveloper** [comment] 2020-08-03 08:28
> Hi @pookdeveloper ,
> 
> Could you provide more details about what are,you experiencing?
> 
> Does it show the `Refresh` notification or not? is the Side Bar visible? Are you using using the correct _case_ for the path?

Yes @alefragnani the notification is showing but when I refresh the panel, it doesn't show the new folders of git projects.
The path that u put is putting in the terminal "pwd" of my folder that contains the projects.

Video of the behaviour: https://share.vidyard.com/watch/pthLc1K7RWeecLqYJjuUaB?

**Comment by alefragnani** [comment] 2020-08-03 22:57
Hi @pookdeveloper ,

Are all (5) folders Git repos? Also, is any of them, or the `ionic` folder itself, a _hard/soft link_ instead of regular folders?

**Comment by pookdeveloper** [comment] 2020-08-03 23:00
> Hi @pookdeveloper ,
> 
> Are all (5) folders Git repos? Also, is any of them, or the `ionic` folder itself, a _hard/soft link_ instead of regular folders?
> 
> 

@alefragnani all are regulars folders and github projects I clone the repo using the gitkrakren app

**Comment by alefragnani** [comment] 2020-08-03 23:17
It should work just fine. It just checks for `.git/config` file (no repo check/ validation btw) and returns the folder. There are only two limitations:

- symlink
- inside remotes

You could check `Toggle Developer Tools` for errors, but today there is no debug/log to turn on.

You should wait for an update to add debug/log messages

**Comment by pookdeveloper** [comment] 2020-08-04 11:19
@alefragnani the problem is simple quote in the routeXD
NOT WORKS:
    "projectManager.git.baseFolders": [
        '/Users/davidgarcia/Desktop/ionic'
    ],

WORKS:
    "projectManager.git.baseFolders": [
        "/Users/davidgarcia/Desktop/ionic"
    ],

**Comment by pookdeveloper** [comment] 2020-08-04 11:24
@alefragnani  I can use regex? for all folders  in "/Users/davidgarcia/Desktop/*", and not use:
        "/Users/davidgarcia/Desktop/ionic",
        "/Users/davidgarcia/Desktop/loopback",....
Thanks

**Comment by alefragnani** [comment] 2020-08-04 12:04
That's great to see it works. I really missed that simple/double quote typo.

About regex, not yet. It's being tracked in #309. Upvote there 👍.
