### ISSUE TITLE
ubuntu 18.04 freezes on hot exit

### ISSUE THREAD

**Issue by sinscary** [alefragnani/vscode-project-manager#304] opened 2019-10-10 05:15 UTC
Hi, I have been facing this issue since the last 4-5 months. If there is an unsaved file and If I try to switch to another project, It shows a popup window asking what should be done for the unsaved file. If I select "Don't Save" everything freezes until unless I kill vs code.

Ubuntu version - 18.04.2
Vscode version - 1.35.1
vscode-project-managet - 10.6.0

**Comment by alefragnani** [comment] 2019-10-10 10:06
Hi @sinscary ,

I’m not sure it has appeared at the same time, but the **Hot Exit** behavior has been updated in VS Code in recent releases (initially discussed in https://code.visualstudio.com/blogs/2016/11/30/hot-exit-in-insiders). In this case, this is a VS Code core feature (not from this extension). To avoid this message, you have to change your User Settings, updating the Hot Exit setting to onExitAndWindowClose (the default value is onExit).

Another possibility would be the same as #207.

Hope this helps

**Comment by sinscary** [comment] 2019-10-10 10:19
Hi @alefragnani the linked issue #207 could possibly the reason. Because I have faced that issue also. If I provide the wrong path while creating a project in `projects.json` and then try to go to that project, ubuntu will freeze. That exact same behavior happens in case of a hot exit also. Looks like VsCode is the culprit here.

**Comment by alefragnani** [comment] 2019-11-17 23:48
Hi @sinscary ,

Are you still having problems with Hot Exit? Have you managed to change the settings and make VS Code works as expected?

Let me know if there is something to fix in the extension, or if it is really caused by VS Code itself.

Thank you

**Comment by alefragnani** [comment] 2020-01-21 23:53
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.

**Closed by alefragnani** 2020-01-21 23:53 UTC
Labels: bug, caused by vscode, duplicate, need more info
