### ISSUE TITLE
Subdir project

### ISSUE THREAD

**Issue by furyscript** [alefragnani/vscode-project-manager#257] opened 2019-03-05 11:55 UTC
Is it possible to save project into a subdirectory/subtree, to reduce the list size when switch project?
In this case we can regroup similar projects.

**Comment by alefragnani** [comment] 2019-03-05 12:53
Hi @furyscript,

What you are describing is a duplicate of #50. Unfortunately, it's not available, yet.

I'm currently planning the roadmap for next releases, and I think it should be available in the near future.

Hope this helps

**Closed** 2019-03-05 12:54 UTC
