### ISSUE TITLE
[BUG] - Icon in Side Bar disappeared

### ISSUE THREAD

**Issue by donoli1st** [alefragnani/vscode-project-manager#601] opened 2022-05-09 09:38 UTC
- Extension version:12.5.0
- VSCode version: 1.67.0
- OS version: Windows 10 1909

**Steps to reproduce**

After upating my VSCode to the newest version, the Icon from the Project-Manager in the Side Bar disappeared. This happend on my machine at home and also on my working machine. The extension is working with the "CTRL" + "SHIFT" + "P"  Codes Like "List Project to Open".. Also i'm able to open my Projects in my projects.json file. But i'd like to have the icon and do it with my mouse. 
I allready uninstalled and reinstalled the extension via the ExtensionsCenter from VSCode with no resualt.
Do you need any Log Files?
I know that this is not much to work with, but maybe you can point me on something, that could produce this Error.

**Comment by donoli1st** [comment] 2022-05-09 12:13
I found the Project Manager
It's now in my Search Icon Tab. Is this wanted so?
![image](https://user-images.githubusercontent.com/46999623/167407420-9e0b81db-1668-47bb-aa5f-c1d39c6980d4.png)

**Comment by alefragnani** [comment] 2022-05-09 12:23
Hi @donoli1st ,

No, it's not that icon. It remains the same for a few years, and the latest extension updated occurred almost 3 months ago, with no changes on Side Bar.

A few _Side Bar icon missing_ issues has faced before, on both my extensions that uses this feature, and it has been always caused by some VS Code issue. Not only _installation process_ but _VS Code updates_ that somehow brakes the extension.

In most of the cases, a **full reiinstall** has fixed the issue. A full reinstall means:

* uninstall the extension
* closes all VS Code windows
* open VS Code again
* reinstall the extension

Doing so, the extension will be _removed_ from Extensions Folder, and VS Code should clear its cache. If you simply remove/install again on the same window (without closing VS Code), it almost never works.

Unfortunately there is nothing else I can do. The icon follows VS Code specifications and no updates has been made for a long time.

Hope this helps

**Comment by donoli1st** [comment] 2022-05-09 15:02
I tryed with the uninstall and reinstall with closing the VSCode.. The Project Manager stays in the search Icon tab.. the global search is also under this icon.. So there are following Dropdowns in the Global Search Tab:

- "Project Manager: Favorites"
- "Project Manager: Git"
- "Project Manager: Help And Feedback"
- "Search"


![image](https://user-images.githubusercontent.com/46999623/167438858-dc550a77-d007-4096-a550-ff1551a8333b.png)


So maybe this gets resolved by the VSCode Team.
Thank you for your Response

**Comment by alefragnani** [comment] 2022-05-10 00:41
The **Title** in this Side Bar is displaying **Search**, which means you are, in fact, in the **Search** Side Bar instead of the **Project Manager**.

Right click in the Activity Bar (the vertical area where the icons are) and search for **Project Manager**. Be sure it is _selected_ and look which icon it is being used. I suppose it is not selected.

I suggest you to use the `View: Reset View Locations` command. It is a VS Code native command, which _resets_ any ui/panel/view customization you have made, resetting these ui components to its default state.

Hope this helps

**Comment by alefragnani** [comment] 2022-08-02 00:26
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2022-08-02 00:26 UTC
Labels: bug, need more info, caused by vscode
