### ISSUE TITLE
[BUG] - Project Manager does not ignore not existing folders

### ISSUE THREAD

**Issue by ilteoood** [alefragnani/vscode-project-manager#644] opened 2022-09-04 09:41 UTC
**Environment/version**

- Extension version: 12.7.0
- VSCode version: 1.71.0
- OS version: macOS Monterey 12.5.1

**Steps to reproduce**

1. Configure 2 folders for project manager, 1 that does not exists and one that exists:
2. Clone your projects in the folder that does exists:
3. Refresh the projects lists:
4. Project manager won't refresh it until the not existing folder will be created or removed from the configuration

**Comment by alefragnani** [comment] 2022-09-05 20:30
Hi @ilteoood ,

I suppose you are referring to `projectManager.XYZ.baseFolders` settings, right? If that's the case:

* The `projectManager.XYZ.baseFolders` setting will _ignore_ any non-existing folder you add, when detecting projects. 
* When you update the setting, the extension detects the change and automatically refresh the projects. But you can _manually_ force the refresh using the `Project Manager: Refresh XYZ Projects` command
* I did a small verification with Git repos, and couldn't reproduce the error you are describing. The extension correctly ignored the non-existing folder and new projects added to the valid folder were correctly detected after refresh.

If I understand correctly your scenario, it seems the extension is working as expected. 

If this is not your scenario (setting, kind of projects, etc), please provide more details of your settings and how to reproduce the error.

Hope this helps

**Comment by alefragnani** [comment] 2022-09-28 00:10
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2022-09-28 00:10 UTC
Labels: bug, need more info
