### ISSUE TITLE
FR: filter VSCode open recent

### ISSUE THREAD

**Issue by Christilut** [alefragnani/vscode-project-manager#320] opened 2020-01-15 10:27 UTC
It would be nice if the `Open recent` menu in under `File` would filter projects that are in the project manager.
My use case is that my most used projects are in the project manager but prototypes and such are in `Open Recent` and now they get pushed out by projects from the project manager that I never open through `Open Recent`.

**Comment by alefragnani** [comment] 2020-01-16 00:28
Hi @Christilut ,

The `Open recent` command stores/controls the _folders/workspaces/files that you opened in VSCode_. Since any project in Project Manager extension is nothing more than a Folder/Workspace, it will be there too (because VSCode opened it). 

The items displayed there are controlled by VSCode itself, with no API available to interact with. So, there is no way to customize the items available.

I only find [one issue](https://github.com/microsoft/vscode/issues/63152) in VS Code repo, which would allow something like this. It's about improving the `Welcome Page` itself, so maybe in the future, we could have this. But unfortunately, the issue is only in their backlog, with no ETA.

Hope this helps.

**Comment by Christilut** [comment] 2020-01-16 08:16
Okay I understand, was afraid it might be out of your control. Too bad.

**Comment by alefragnani** [comment] 2021-07-17 03:19
I'm sorry to say, but I’m closing this issue because it depends on a VS Code API, and the linked issue was closed by the VS Code Team, with no support to the necessary API. Being so, it won't be possible to deliver such feature.

Thanks for your understanding.

**Closed by alefragnani** 2021-07-17 03:19 UTC
Labels: depends on (in coma), enhancement
