### ISSUE TITLE
All projects deleted / reset / gone

### ISSUE THREAD

**Issue by adammendoza** [alefragnani/vscode-project-manager#279] opened 2019-06-03 00:23 UTC
All the projects that I had setup are gone. Obviously, I mean the link form the extension. The actual directories still exist but now I have to set up all project short-cuts again. I'm not sure if it was due to some update in Visual Studio Code or another extension, or this extension. 

Thanks!

**Comment by supdegrave** [comment] 2019-06-03 07:36
Probably a duplicate of https://github.com/alefragnani/vscode-project-manager/issues/277.

**Comment by alefragnani** [comment] 2019-06-03 16:47
@adammendoza if you miss only the "Saved / Favorites" projects, please subscribe to #277, as sugested by @supdegrave, otherwise (also missing auto-detected projects, it could be a new issue.

@supdegrave thanks for your help  👏

**Comment by ebro** [comment] 2019-06-04 07:15
This has also happened to me. The projects.json file in folder /Users/{user}/Library/Application Support/Code/User/globalStorage/alefragnani.project-manager/ was deleted. I was able to restore the file via Timemachine and all my settings were back.

**Comment by alefragnani** [comment] 2019-06-05 23:48
@ebro , I’m sorry to hear that, but as you can see in #277 , no idea why that is happening 😞 .

Please, subscribe to #277 to follow the news.

**Closed** 2019-06-05 23:48 UTC
Labels: duplicate, need more info
