### ISSUE TITLE
[BUG] - please help to fix bug .. for my fault using this svc and i understand now all but i cant how to start againe i can not create to cause multiple error .. 

### ISSUE THREAD

**Issue by kuysjhay18** [alefragnani/vscode-project-manager#782] opened 2024-12-31 07:56 UTC
**Environment/version**

- Extension version:
- VSCode version: 
- OS version: 

**Steps to reproduce**

1. 
2.

**Comment by alefragnani** [comment] 2024-12-31 14:31
duplicate of #781

**Closed by alefragnani** 2024-12-31 14:31 UTC
Labels: bug
