### ISSUE TITLE
Apply `sortList` setting to Side Bar

### ISSUE THREAD

**Issue by massimo-cassandro** [alefragnani/vscode-project-manager#382] opened 2020-05-21 08:27 UTC
Maybe I'me doing something wrong, but the `"projectManager.sortList": "Recent"` hasn't any effect for me...

Project Manager 11.0
VScode 1.45.1 on OSX 10.15.4

Thanks

**Comment by alefragnani** [comment] 2020-05-21 11:19
Hi @massimo-cassandro ,

Could you please provide more details about it? Which scenarios you noticed it is not working properly?

Thank you

**Comment by massimo-cassandro** [comment] 2020-05-21 12:12
Hi @alefragnani ,
thanks for your quick answer.

I've about 20 projects in my vscode *project manager favorites* panel, they are listed by name, as per default option. Most of them refer to the .code-workspace.
I've tried to change the `projectManager.sortList` parameter both thru the vscode sentting interface and directly in the `settings.json` file.

I've tried all options, restarting vscode too, but nothing is changed.

This is a portion of my `project.json` file:

```
[
	{
		"name": "_dev-utilities",
		"rootPath": "$home/Sites/_dev-utilities",
		"paths": [],
		"group": "",
		"enabled": true
	},
       {
		"name": "js-fileuploader",
		"rootPath": "$home/Sites/js-file-uploader/fileuploader.code-workspace",
		"paths": [],
		"group": "",
		"enabled": true
	},
...
]
```

Hope this can help

bye

**Comment by alefragnani** [comment] 2020-05-21 13:04
You are welcome :+1. 

The **Side Bar** does not respect that setting. It will always display the projects sorted by name. Only the `Command Palette` supports that.

Do you really think the **Side Bar** should respect that setting? If that’s the case, I could add as an enhancement in upcoming releases.

Hope this helps

**Comment by massimo-cassandro** [comment] 2020-05-21 13:14
> Do you really think the Side Bar should respect that setting?

I personally use ONLY the side bar, since I found it is the quickiest way to load projects, another really useful option would be the ability to group projects in folders within the side bar (maybe you've already planned it...)

Thanks again and congratulations for your excellent extension
Bye

**Comment by alefragnani** [comment] 2020-05-21 16:05
Thank you for your kind words! That's great to hear you like the extension, and enjoys using the Side Bar.

About grouping, is already being tracked in #50 .

Hope this helps

**Comment by alefragnani** [comment] 2020-09-06 19:03
I don't know what I had in mind back then, but I didn't noticed that the same request has been requested a few days earlier (#366) 😕 

So, I'm closing this issue as a #duplicate of #366. Feel free to upvote the other issue.

I think this could be out in the upcoming releases. Stay tuned

**Closed** 2020-09-06 19:03 UTC
Labels: duplicate, enhancement, side bar
